"""added confirmed column to user table

Revision ID: 617c2484a85f
Revises: 3de1ad8a28d6
Create Date: 2018-07-12 08:44:09.391312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617c2484a85f'
down_revision = '3de1ad8a28d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
